/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TCallFunc extends Token
{
    public TCallFunc()
    {
        super.setText("function");
    }

    public TCallFunc(int line, int pos)
    {
        super.setText("function");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCallFunc(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCallFunc(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCallFunc text.");
    }
}
