/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TComa extends Token
{
    public TComa()
    {
        super.setText(",");
    }

    public TComa(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TComa(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComa(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TComa text.");
    }
}
