/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TDoisPontos extends Token
{
    public TDoisPontos()
    {
        super.setText(":");
    }

    public TDoisPontos(int line, int pos)
    {
        super.setText(":");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDoisPontos(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDoisPontos(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDoisPontos text.");
    }
}
