/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TLbracket extends Token
{
    public TLbracket()
    {
        super.setText("[");
    }

    public TLbracket(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLbracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLbracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLbracket text.");
    }
}
