/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TMenor extends Token
{
    public TMenor()
    {
        super.setText("<");
    }

    public TMenor(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMenor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMenor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMenor text.");
    }
}
