/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TParDir extends Token
{
    public TParDir()
    {
        super.setText(")");
    }

    public TParDir(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TParDir(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParDir(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TParDir text.");
    }
}
