/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TRbracket extends Token
{
    public TRbracket()
    {
        super.setText("]");
    }

    public TRbracket(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRbracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRbracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRbracket text.");
    }
}
