/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TSoma extends Token
{
    public TSoma()
    {
        super.setText("+");
    }

    public TSoma(int line, int pos)
    {
        super.setText("+");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSoma(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSoma(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSoma text.");
    }
}
