/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.node;

import NonNewman.analysis.*;

public final class TSubt extends Token
{
    public TSubt()
    {
        super.setText("-");
    }

    public TSubt(int line, int pos)
    {
        super.setText("-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSubt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSubt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSubt text.");
    }
}
