/* This file was generated by SableCC (http://www.sablecc.org/). */

package NonNewman.analysis;

import NonNewman.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTEntrada(TEntrada node);
    void caseTCallFunc(TCallFunc node);
    void caseTLambda(TLambda node);
    void caseTTipo(TTipo node);
    void caseTCondLog(TCondLog node);
    void caseTCondSint(TCondSint node);
    void caseTSoma(TSoma node);
    void caseTSubt(TSubt node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTAtribuidor(TAtribuidor node);
    void caseTMenor(TMenor node);
    void caseTMaior(TMaior node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTLbracket(TLbracket node);
    void caseTRbracket(TRbracket node);
    void caseTComa(TComa node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTNumero(TNumero node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
}
